import streamlit as sl
from modules import display_my_custom_component, display_post, display_genai_advice, display_calories_leaderboard_global, display_friends_leaderboard
from data_fetcher import get_user_posts, get_user_profile, get_genai_advice, get_user_friends,get_friends_calories_list,get_global_calories_list

def display_community(user_id):
    user_profile = get_user_profile(user_id)
    sl.title("❤️ Community Page")
    sl.subheader(f" {user_profile['full_name']}'s")

    tab1, tab2, tab3, tab4 = sl.tabs(["👥 Friends' Posts", "GenAI Advice", "👤 My Posts", "🏆 Leaderboards"])

    with tab1:
        if len(get_user_friends(user_id)) <= 0:
            sl.info("You haven't added any friends yet!")
        else:
            display_post(user_id)

    with tab2:
        display_genai_advice(user_id)

    with tab3:
        user_posts = get_user_posts(user_id)
        if user_posts:
            sl.subheader("📝 Your Posts")
            sl.markdown("---")
            user_posts.sort(key=lambda post: post.get('timestamp', ''), reverse=True)
            # Generated by GPT 4o
            for post in user_posts:
                # sl.write(post) #For debugging
                image_url = post.get('image', '')
                if image_url and image_url.startswith("http"):
                    sl.image(image_url, width=300)

                sl.markdown(post.get('content', 'No content available.'))
                timestamp = post.get('timestamp', '🕒 No timestamp')
                sl.markdown(f"**{timestamp}**")
                sl.markdown("---")
        else:
            sl.info("You haven't posted anything yet.")

    with tab4:
        sl.subheader("🏆 Leaderboards")
        leaderboard_type = sl.radio("Select Leaderboard:", ["Global", "Friends"])

        if leaderboard_type == "Global":
            display_calories_leaderboard_global(streamlit_module=sl)
        elif leaderboard_type == "Friends":
            display_friends_leaderboard(user_id=user_id, streamlit_module=sl)