import streamlit as sl
from modules import display_my_custom_component, display_post
from data_fetcher import get_user_posts, get_user_profile

def display_community(user_id):
    user_profile = get_user_profile(user_id)
    sl.title("❤️ Community Page")
    sl.subheader(f" {user_profile['full_name']}'s")

    tab1, tab2 = sl.tabs(["👥 Friends' Posts", "👤 My Posts"])

    with tab1:
        display_post(user_id) 

    with tab2:
        sl.subheader("📝 Your Posts")
        sl.markdown("---")
        user_posts = get_user_posts(user_id)
        if user_posts:
            user_posts.sort(key=lambda post: post.get('timestamp', ''), reverse=True)
            # Generated by GPT 4o
            for post in user_posts:
               # sl.write(post) #For debugging
                image_url = post.get('image', '')
                if image_url and image_url.startswith("http"):
                    sl.image(image_url, width=300)

                sl.markdown(post.get('content', 'No content available.'))
                timestamp = post.get('timestamp', '🕒 No timestamp')
                sl.markdown(f"**{timestamp}**")
                sl.markdown("---")
        else:
            sl.info("You haven't posted anything yet.")

