import streamlit as sl
from modules import display_my_custom_component, display_post, display_genai_advice, display_global_leaderboard, display_friends_leaderboard,post_creation_box, add_friend_box
from data_fetcher import get_user_posts, get_user_profile, get_genai_advice, get_user_friends,get_friends_calories_list,get_global_calories_list, insert_user_post, get_global_distance_list, get_global_steps_list, get_friends_distance_list, get_friends_steps_list

def display_community(user_id):

    sl.title("Community Page")
    user_profile = get_user_profile(user_id)
    
    sl.subheader(f" {user_profile['full_name']}'s")

    tab1, tab2, tab3, tab4 = sl.tabs(["👥 Friends' Posts", "GenAI Advice", "👤 My Posts", "🏆 Leaderboards"])

    with tab1:
        if len(get_user_friends(user_id)) <= 0:
            sl.info("You haven't added any friends yet!")
        else:
            add_friend_box(user_id)
            sl.markdown("---")
            display_post(user_id)

    with tab2:
        display_genai_advice(user_id)

    with tab3:
        user_posts = get_user_posts(user_id)
        if user_posts:
            post_creation_box(user_id)
            sl.markdown("---")
            user_posts.sort(key=lambda post: post.get('timestamp', ''), reverse=True)
            # Generated by GPT 4o
            for post in user_posts:
                # sl.write(post) #For debugging
                image_url = post.get('image', '')
                if image_url and image_url.startswith("http"):
                    sl.image(image_url, width=300)

                sl.markdown(post.get('content', 'No content available.'))
                timestamp = post.get('timestamp', '🕒 No timestamp')
                sl.markdown(f"**{timestamp}**")
                sl.markdown("---")
        else:
            sl.info("You haven't posted anything yet.")

    with tab4:
        sl.markdown("---")
        sl.subheader("🏆 Leaderboards")

        leaderboard_type = sl.radio("Select Leaderboard:", ["Global", "Friends"], horizontal=True)
        metric = sl.radio("Choose Category:", ["calories", "distance", "steps"], horizontal=True)

        # Map metrics to fetch functions
        global_funcs = {
            "calories": get_global_calories_list,
            "distance": get_global_distance_list,
            "steps": get_global_steps_list
        }

        friends_funcs = {
            "calories": get_friends_calories_list,
            "distance": get_friends_distance_list,
            "steps": get_friends_steps_list
        }

        if leaderboard_type == "Global":
            display_global_leaderboard(metric=metric, streamlit_module=sl, get_leaderboard_func=global_funcs[metric])
        elif leaderboard_type == "Friends":
            display_friends_leaderboard(user_id=user_id, streamlit_module=sl, get_friends_funcs=friends_funcs)
